services:
  frontend:
    build:
      context: ./my-remix-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./my-fastapi-app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - FRONTEND_URL=http://frontend:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
